name: CoinMaterial
version: ${project.version}
main: coinmaterial.coinmaterial.CoinMaterial
api-version: 1.13
commands:
  CoinMaterial:
    description: Перезагрузка плагина
    permission: CoinMaterial.reload
    usage: /coinmaterial reload
  money:
    description: Узнать баланс
    usage: /money
  wallet:
    description: Получить деньги со счёта
    usage: /wallet [count]
  pay:
    description: Перевод денег игроку
    usage: /pay [nickname] [count]
