name: CoinMaterial
version: ${project.version}
main: coinmaterial.coinmaterial.CoinMaterial
api-version: 1.13
commands:
  CoinMaterial:
    description: Перезагрзка плагина
    permission: <plugin name>.CoinMaterial
    usage: /coinmaterial reload
  money:
    description: Узнать баланс счёта
    usage: /money
  wallet:
    description: Получить свои деньги наличкой
    usage: /wallet [count]
  pay:
    description: Перевод денег игроку
    usage: /pay [nickname][count]
